### ISSUE TITLE
Release doesn't work on warden, due to public_ip_address resolution.

### ISSUE THREAD

**Issue by karlkfi** [cf-platform-eng/mesos-boshrelease#5]
Current:

```
if public_ip=$(public_ip_address); then
  public_ip=$public_ip
else
  public_ip=<%= public_ip %>
fi
```

Problem:
`public_ip_address()` does not fail, it just returns an empty string. So the else is never used.

Desired:

```
public_ip=$(public_ip_address)
if [ -z $public_ip ]; then
  public_ip=<%= public_ip %>
fi
```

This will properly fall back to the public_ip if not on aws/gce. 
If no vip is provided, then public_ip will be the private_ip, which is what's wanted for warden.

**Comment by frodenas** [comment]
Thanks @karlkfi, fixed at https://github.com/cf-platform-eng/mesos-boshrelease/commit/0b657416a82b6ec3aa7f4e843e027c4814b4a1e6.
