### ISSUE TITLE
Several places set the hostname as the domain name, even when dns is disabled.

### ISSUE THREAD

**Issue by karlkfi** [cf-platform-eng/mesos-boshrelease#6]
zookeeper, jenkins, and docker are all suppossed to set the hostname to the dns record when `public_hostname()` is empty. 

Firstly, the else statement never executes, due to #5. 

Secondly, even if it did, it would be wrong when dns is disabled. 

Unfortunately, there's not a great way to detect that dns is enabled from within a template. The only way I know of is to set a new custom property toggle to let the jobs know if bosh dns is enabled.

**Comment by frodenas** [comment]
Thanks @karlkfi, fixed at https://github.com/cf-platform-eng/mesos-boshrelease/commit/b8adfbe8a123709c6a208ddeefcb5ee66ad7b898. The release doesn't need to set the hostname anymore.
