### ISSUE TITLE
Add warden deployment manifest template

### ISSUE THREAD

**Issue by karlkfi** [cf-platform-eng/mesos-boshrelease#7]
Here's my working warden template (with #5 fixed locally):
https://gist.github.com/karlkfi/220af5c51e88e7d3f340

I chopped out everything but zk/mesos/marathon, but the others shouldn't be too hard to add back in.
You'll want to templatize it to include it in the repo.

Update: Yes, it has more subnets defined than it needs. I just copied CF's and used a few of them.

**Comment by frodenas** [comment]
Thanks @karlkfi, added a bosh-lite deployment manifest at https://github.com/cf-platform-eng/mesos-boshrelease/commit/bdb9e764039fe0b961762b8104291191ca2dbfb6.

**Comment by karlkfi** [comment]
warden is the cpi, technically. bosh-lite is just the fast way to deploy bosh on warden.
